CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE TABLE "Players" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Game" character varying(50) NOT NULL,
        "Team" character varying(100),
        "BasePrice" numeric(18,2) NOT NULL,
        "CurrentPrice" numeric(18,2) NOT NULL,
        "TotalShares" integer NOT NULL,
        "AvailableShares" integer NOT NULL,
        "Rating" numeric(3,2),
        "PopularityScore" integer NOT NULL,
        "LastUpdated" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Players" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE TABLE "Teams" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Game" character varying(50) NOT NULL,
        "BasePrice" numeric(18,2) NOT NULL,
        "CurrentPrice" numeric(18,2) NOT NULL,
        "TotalShares" integer NOT NULL,
        "AvailableShares" integer NOT NULL,
        "Ranking" integer,
        "LastUpdated" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Teams" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" character varying(50) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "PasswordHash" character varying(255) NOT NULL,
        "Balance" numeric(18,2) NOT NULL,
        "Level" integer NOT NULL,
        "TotalTrades" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "LastLoginAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "IsEmailVerified" boolean NOT NULL,
        "VerificationToken" text,
        "VerificationTokenExpires" timestamp with time zone,
        "ResetToken" text,
        "ResetTokenExpires" timestamp with time zone,
        "IsKycVerified" boolean NOT NULL,
        "KycStatus" text,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE TABLE "Matches" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PlayerId" integer,
        "TeamId" integer,
        "Opponent" character varying(100),
        "Result" character varying(10),
        "PlayerRating" numeric(3,2),
        "IsMVP" boolean NOT NULL,
        "Tournament" character varying(100),
        "TournamentTier" integer,
        "MatchDate" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Matches" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Matches_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Matches_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE TABLE "PriceHistory" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PlayerId" integer,
        "TeamId" integer,
        "Price" numeric(18,2) NOT NULL,
        "Volume" integer NOT NULL,
        "RecordedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PriceHistory" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PriceHistory_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_PriceHistory_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE TABLE "Achievements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Type" integer NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "AchievedAt" timestamp with time zone NOT NULL,
        "RewardAmount" numeric(18,2),
        "RelatedData" text,
        CONSTRAINT "PK_Achievements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Achievements_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE TABLE "AuditLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Action" character varying(100) NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "Details" character varying(1000),
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE TABLE "Notifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Type" character varying(50) NOT NULL,
        "Message" character varying(500) NOT NULL,
        "IsRead" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "RelatedEntityId" text,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE TABLE "Orders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "PlayerId" integer,
        "TeamId" integer,
        "Type" integer NOT NULL,
        "Shares" integer NOT NULL,
        "Price" numeric(18,2) NOT NULL,
        "Status" integer NOT NULL,
        "FilledShares" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Orders_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE TABLE "Transactions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Type" integer NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "CompletedAt" timestamp with time zone,
        "Notes" character varying(500),
        "ExternalTransactionId" character varying(255),
        CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Transactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE TABLE "UserPortfolios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "PlayerId" integer,
        "TeamId" integer,
        "Shares" integer NOT NULL,
        "AveragePrice" numeric(18,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_UserPortfolios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserPortfolios_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_UserPortfolios_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_UserPortfolios_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE TABLE "Trades" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BuyOrderId" integer NOT NULL,
        "SellOrderId" integer NOT NULL,
        "PlayerId" integer,
        "TeamId" integer,
        "Shares" integer NOT NULL,
        "Price" numeric(18,2) NOT NULL,
        "Commission" numeric(18,2) NOT NULL,
        "Tax" numeric(18,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Trades" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Trades_Orders_BuyOrderId" FOREIGN KEY ("BuyOrderId") REFERENCES "Orders" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Trades_Orders_SellOrderId" FOREIGN KEY ("SellOrderId") REFERENCES "Orders" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Trades_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Trades_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_Achievements_UserId" ON "Achievements" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_Matches_PlayerId" ON "Matches" ("PlayerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_Matches_TeamId" ON "Matches" ("TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_Orders_PlayerId" ON "Orders" ("PlayerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_Orders_TeamId" ON "Orders" ("TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Players_Name_Game" ON "Players" ("Name", "Game");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_PriceHistory_PlayerId" ON "PriceHistory" ("PlayerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_PriceHistory_TeamId" ON "PriceHistory" ("TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Teams_Name_Game" ON "Teams" ("Name", "Game");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_Trades_BuyOrderId" ON "Trades" ("BuyOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_Trades_PlayerId" ON "Trades" ("PlayerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_Trades_SellOrderId" ON "Trades" ("SellOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_Trades_TeamId" ON "Trades" ("TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_Transactions_UserId" ON "Transactions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_UserPortfolios_PlayerId" ON "UserPortfolios" ("PlayerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE INDEX "IX_UserPortfolios_TeamId" ON "UserPortfolios" ("TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_UserPortfolios_UserId_PlayerId_TeamId" ON "UserPortfolios" ("UserId", "PlayerId", "TeamId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250830025915_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250830025915_InitialCreate', '8.0.0');
    END IF;
END $EF$;
COMMIT;

